### PR TITLE
Fix ; in chart plugins

### PR DESCRIPTION
**Pull request by madeITBelgium**

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Blade scripts dont need a semicolon at the end, what error / issue is this PR fixing?

**Comment by Naoray** [comment]
@ConsoleTVs it d removing the ";" not adding it

**Comment by madeITBelgium** [comment]
@ConsoleTVs I'm deleting the semicolon because it is not necessary. Sometimes semicolon is visible.

**Comment by ConsoleTVs** [comment]
Ah jezz, this is completly correct. Sorry guys, i swapped both lines!

**Pull request merged**
